FROM debian:stable-slim as builder

ARG ETHEREUM_PACKAGE=https://github.com/kurtosis-tech/ethereum-package
ARG ETHEREUM_PACKAGE_BRANCH="main"

RUN apt-get update && apt-get -y upgrade && apt-get install -y --no-install-recommends \
  libssl-dev \
  ca-certificates \
  jq \
  git \
  curl \
  make \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

RUN git clone "${ETHEREUM_PACKAGE}";

# PULL all of the dependencies in here
# Known dependencies
# - prometheus
# - postgres
# - db-adminer
# - redis
ARG PROMETHEUS_PACKAGE=https://github.com/kurtosis-tech/prometheus-package
ARG PROMETHEUS_BRANCH="main"
ARG POSTGRES_PACKAGE=https://github.com/kurtosis-tech/postgres-package
ARG POSTGRES_BRANCH="main"
ARG DB_ADMINER_PACKAGE=https://github.com/bharath-123/db-adminer-package
ARG DB_ADMINER_BRANCH="main"
ARG REDIS_PACKAGE=https://github.com/kurtosis-tech/redis-package
ARG REDIS_BRANCH="main"

RUN git clone "${PROMETHEUS_PACKAGE}"
RUN git clone "${POSTGRES_PACKAGE}"
RUN git clone "${DB_ADMINER_PACKAGE}"
RUN git clone "${REDIS_PACKAGE}"

# NOTE: making the ethereum package reference locally pulled dependencies
RUN sed -i '$ a\\nreplace:\n    github.com/kurtosis-tech/prometheus-package: ../prometheus-package\n    github.com/kurtosis-tech/postgres-package: ../postgres-package\n    github.com/bharath-123/db-adminer-package: ../db-adminer-package\n    github.com/kurtosis-tech/redis-package: ../redis-package' /ethereum-package/kurtosis.yml

FROM scratch

COPY --from=builder /ethereum-package /ethereum-package
COPY --from=builder /prometheus-package /prometheus-package
COPY --from=builder /postgres-package /postgres-package
COPY --from=builder /db-adminer-package /db-adminer-package
COPY --from=builder /redis-package /redis-package
