FROM debian:stable-slim as builder

ARG PACKAGE=https://github.com/kurtosis-tech/ethereum-package
ARG PACKAGE_BRANCH="main"

RUN apt-get update && apt-get -y upgrade && apt-get install -y --no-install-recommends \
  libssl-dev \
  ca-certificates \
  jq \
  git \
  curl \
  make \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

RUN git clone "${PACKAGE}";

# PULL all of the dependencies in here
# Known dependencies
# - prometheus
# - db-adminer
# - redis
ARG PROMETHEUS_PACKAGE=https://github.com/kurtosis-tech/prometheus-package
ARG PROMETHEUS_BRANCH="main"
ARG DB_ADMINER_PACKAGE=https://github.com/bharath-123/db-adminer-package
ARG DB_ADMINER_BRANCH="main"
ARG REDIS_PACKAGE=https://github.com/kurtosis-tech/redis-package
ARG REDIS_BRANCH="main"


RUN git clone "${PROMETHEUS_PACKAGE}"
RUN git clone "${DB_ADMINER_PACKAGE}"
RUN git clone "${REDIS_PACKAGE}"

RUN ls -lah

FROM scratch

COPY --from=builder /ethereum-package /ethereum-package
COPY --from=builder /prometheus-package /prometheus-package
COPY --from=builder /db-adminer-package /db-adminer-package
COPY --from=builder /redis-package /redis-package

# RUN ls -lah